const swaggerAutogen = require('swagger-autogen')({openapi: '3.0.0'});

const doc = {
    info: {
        version: "1.0.0",
        title: "Project Skill Test Aji Raksa Kumala",
        description: "Documentation automatically generated by the <b>swagger</b> module."
    },
    host: `localhost:4002`,
    basePath: "/",
    schemes: ['http', 'https'],
    consumes: ['application/json'],
    produces: ['application/json'],
    tags: [
        {
            "name": "book-controller"
        },
        {
            "name": "user-controller"
        },
        {
            "name": "publisher-controller"
        },
        {
            "name": "my-authentication-controller"
        }
    ],
    components: {
        securitySchemes:{
            tokenAuth: {
                type: 'http',
                scheme: 'bearer',
                in: "header",
                name: "Authorization",
                description: "Masukan token disini ..."
            }
        }
    },
    '@definitions': {
        RegistrationRequest: {
            type: 'object',
            properties: { 
                email: { 
                    "type": "string"
                },
                password: { 
                    "type": "string"
                },
                firstName: { 
                    "type": "string"
                },
                lastName: { 
                    "type": "string"
                },
            }
        },
        UserDto: {
            type: 'object',
            properties: { 
                email: { 
                    "type": "string"
                },
                firstName: { 
                    "type": "string"
                },
                lastName: { 
                    "type": "string"
                },
            }
        },
        JwtRequest: {
            type: 'object',
            properties: { 
                email: { 
                    "type": "string",
                    "example": "ajiraksakumala@gmail.com"
                },
                password: { 
                    "type": "string",
                    "example": "12345Aji$"
                },
            } 
        },
        JwtResponse: {
            type: 'object',
            properties: { 
                token: {
                    "type": "string"
                },
            }
        },
        Book: {
            type: 'object',
            properties: { 
                id: { 
                    "type": "integer",
                    "format": 'int32'
                },
                title: { 
                    "type": "string"
                },
                author: { 
                    "type": "string"
                },
                isbn: { 
                    "type": "string"
                },
                publisherId: { 
                    "type": "integer",
                    "format": 'int32'
                },
            } 
        },
        BookDto: {
            type: 'object',
            properties: { 
                id: { 
                    "type": "integer",
                    "format": 'int32'
                },
                title: { 
                    "type": "string"
                },
                author: { 
                    "type": "string"
                },
                isbn: { 
                    "type": "string"
                },
                publisher: { 
                    "type": "string"
                },
            } 
        },
        AddBookRequest: {
            type: 'object',
            properties: { 
                title: { 
                    "type": "string"
                },
                author: { 
                    "type": "string"
                },
                isbn: { 
                    "type": "string"
                },
                publisherId: { 
                    "type": "integer",
                    "format": 'int32'
                },
            } 
        },
        Publisher: {
            type: 'object',
            properties: { 
                id: { 
                    "type": "integer",
                    "format": 'int32'
                },
                name: { 
                    "type": "string"
                },
            } 
        }
    },
    definitions: {
        HttpResponseModelUserDto: {
            status: 1,
            "message": "string",
            "data": {
                $ref: '#/definitions/UserDto'
            }
        },
        HttpResponseModelJwtResponse: {
            status: 1,
            "message": "string",
            "data": {
                $ref: '#/definitions/JwtResponse'
            }
        },
        HttpResponseModelErrorToken: {
            status: 0,
            "message": "string",
            "data": null
        },
        HttpResponseModelPublisher: {
            status: 1,
            "message": "string",
            "data": {
                $ref: '#/definitions/Publisher'
            }
        },
        HttpResponseModelIterablePublisher: {
            status: 1,
            "message": "string",
            "data": [
                {
                    $ref: '#/definitions/Publisher'
                }
            ]
        },
        HttpResponseModelBook: {
            status: 1,
            "message": "string",
            "data": {
                $ref: '#/definitions/Book'
            }
        },
        HttpResponseModelBookDto: {
            status: 1,
            "message": "string",
            "data": {
                $ref: '#/definitions/BookDto'
            }
        },
        HttpResponseModelListBookDto: {
            status: 1,
            "message": "string",
            "data": [
                {
                    $ref: '#/definitions/BookDto'
                }
            ]
        }
    }
}

const outputFile = './swagger-output.json'
const endpointsFiles = ['./app.js']

swaggerAutogen(outputFile, endpointsFiles, doc).then(() => {
    require('./bin/www') // Your project's root file
})